[project]
name          = "django-active-link"
version       = "0.3.0"
description   = "The best and simplest way to highlight active links in your Django app."
license       = "BSD-3-Clause"
authors       = [
    {name = "Valery Melou", email = "valerymelou@gmail.com"},
]
maintainers   = [
    {name = "Frederich Pedersen", email = "frodo@hobbits.dk"},
]
readme        = "README.rst"
keywords      = ["django", "active", "link", "django-active-link", "sidebar", "navbar"]
classifiers   = [
    'Development Status :: 5 - Production/Stable',
    'Framework :: Django',
    'Framework :: Django :: 5.2',
    'Framework :: Django :: 6.0',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Intended Audience :: Developers',
    'Natural Language :: English',
]
requires-python = ">=3.10"

dependencies    = [
    "django>=5.2"
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-django>=4.11.1",
    "tox>=4.32.0",
    "pre-commit>=4.6.0",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"


[project.urls]
Repository    = "https://github.com/valerymelou/django-active-link"
Documentation = "https://django-active-link.readthedocs.io/"
"Bug Tracker" = "https://github.com/valerymelou/django-active-link/issues"
"codecov"     = "https://codecov.io/gh/valerymelou/django-active-link"