[tox]
envlist =
    lint
    py{3.10,3.11,3.12,3.13,3.14}-django-52
    py{3.12,3.13,3.14}-django-60

[testenv]
description = run unit tests
require_locked_deps = true
deps =
    pytest
    pytest-django
    codecov>=2.0.0
    django-52: Django >=5.2,<6.0
    django-60: Django >=6.0,<6.1
commands =
    coverage run -m pytest
    coverage xml
